export const routeNames = {
  Auth: "Auth",
  Login: "Login",
  Register: "Register",
  Main: "Main",
  Home: "Home",
  PlannerTab: "PlannerTab",
  Profile: "Profile",
  PlannerTrip: "PlannerTrip",
  Onboarding: "Onboarding",
  Pricing: "Pricing",
  Admin: "Admin",
  Invite: "Invite",
  ShareTrip: "ShareTrip",
  TripDetail: "TripDetail",
} as const;
