/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/saved`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/invite/[token]`, params: Router.UnknownInputParams & { token: string | number; } } | { pathname: `/planner/[tripId]`, params: Router.UnknownInputParams & { tripId: string | number; } } | { pathname: `/planner/[tripId]/collaboration`, params: Router.UnknownInputParams & { tripId: string | number; } } | { pathname: `/share/[shareId]`, params: Router.UnknownInputParams & { shareId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landing`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/trips`; params?: Router.UnknownOutputParams; } | { pathname: `/invite/[token]`, params: Router.UnknownOutputParams & { token: string; } } | { pathname: `/planner/[tripId]`, params: Router.UnknownOutputParams & { tripId: string; } } | { pathname: `/planner/[tripId]/collaboration`, params: Router.UnknownOutputParams & { tripId: string; } } | { pathname: `/share/[shareId]`, params: Router.UnknownOutputParams & { shareId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/landing${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/trips${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/saved`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/trips`; params?: Router.UnknownInputParams; } | `/invite/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/planner/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/planner/${Router.SingleRoutePart<T>}/collaboration${`?${string}` | `#${string}` | ''}` | `/share/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/invite/[token]`, params: Router.UnknownInputParams & { token: string | number; } } | { pathname: `/planner/[tripId]`, params: Router.UnknownInputParams & { tripId: string | number; } } | { pathname: `/planner/[tripId]/collaboration`, params: Router.UnknownInputParams & { tripId: string | number; } } | { pathname: `/share/[shareId]`, params: Router.UnknownInputParams & { shareId: string | number; } };
    }
  }
}
