export const STRINGS = {
  searchPlaceholder: "Search here",
  profileAvatarLabel: "Profile",
  searchScreenTitle: "Search",
  chooseStartingPoint: "Choose starting point",
  chooseDestination: "Choose destination",
  useCurrentLocation: "Use current location",
  recentSearches: "RECENT SEARCHES",
  noResults: "No places found",
  searchInputPlaceholder: "Search places",
  loading: "Loading...",
  travelModeDrive: "Drive",
  travelModeWalk: "Walk",
  travelModeBike: "Bike",
  routeViaLabel: "via best route",
  routeStart: "Start",
  routeSteps: "Steps ▾",
  routeStepsExpanded: "Steps ▴",
  routeNoSteps: "No steps available",
  routePreviewEmpty: "Select origin and destination to preview route.",
  waypointPlaceholder: "Add stop",
  waypointDragHandle: "≡",
  waypointRemove: "✕",
  savedRoutesTitle: "Saved routes",
  savedRoutesEmpty: "No saved routes yet",
  savedRoutesDelete: "Delete",
  savedRoutesFab: "Save route",
  savedRoutesUnnamed: "Unnamed route",
  savedRoutesNameSeparator: " to ",
  mapPermissionRequired: "Location permission is required for live tracking.",
  searchErrorFallback: "Unable to load places right now.",
  signInTitle: "Sign in",
  signInEmail: "Email",
  signInPassword: "Password",
  signInButton: "Sign in",
  signInRegisterCta: "Create an account",
  registerTitle: "Create account",
  registerName: "Name",
  registerButton: "Register",
  registerBackToSignIn: "Already have an account? Sign in",
  onboardingTitle: "Welcome to Viazo",
  onboardingSubtitle: "Plan trips on the map, sync itineraries from the web, and build routes between your stops.",
  onboardingContinue: "Continue",
  tripsTabTitle: "Trips",
  tripsYourSection: "Your itineraries",
  tripsCommunitySection: "Community",
  tripsEmpty: "No itineraries yet. Create one to get started.",
  tripsCreateTitle: "New itinerary",
  tripsCreateName: "Name",
  tripsCreateSubmit: "Create",
  tripsCreateCancel: "Cancel",
  tripDetailTitle: "Itinerary",
  tripStatusDraft: "Draft",
  tripStatusFinalized: "Finalized",
  tripPublic: "Public",
  tripPrivate: "Private",
  tripWaypoints: "Stops",
  tripOpenMap: "Open on map",
  tripRoutePreview: "Preview route",
  tripFinalize: "Finalize",
  tripReopen: "Reopen for editing",
  tripPublish: "Publish to community",
  tripUnpublish: "Remove from community",
  tripDelete: "Delete itinerary",
  tripDeleteConfirm: "Delete this itinerary? This cannot be undone.",
  tripShare: "Share link",
  tripLoadError: "Could not load itinerary.",
  tripNeedTwoStops: "Add at least two stops to this itinerary (on the web) before previewing a route.",
  profileTitle: "Account",
  profilePlan: "Plan",
  profileSignOut: "Sign out",
  profileEmail: "Email",
  commonError: "Something went wrong",
  tabMap: "Map",
  tabTrips: "Trips",
  tabSaved: "Saved",
  tabProfile: "Profile",
} as const;
